# Generated by Django 3.2.10 on 2022-01-10 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cruise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('startPort', models.CharField(max_length=128)),
                ('endPort', models.CharField(max_length=128)),
                ('maxBerths', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='patent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('S', 'Schiffer'), ('W', 'Wachführer'), ('C', 'Crewmitglied')], default='C', max_length=1)),
                ('Since', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sailor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='TESTNUTZER', max_length=256)),
                ('givenName', models.CharField(default='TEST', max_length=128)),
                ('sirName', models.CharField(default='NUTZER', max_length=128)),
                ('ownedPatent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cruises.patent')),
            ],
        ),
        migrations.CreateModel(
            name='license',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('SHS', 'Sporthochseeschifferschein'), ('SSS', 'Sportseeschifferschein'), ('SKS', 'Sportküstenschifferschein'), ('SBS', 'Sportbootführerschein See'), ('SBB', 'Sportbootführerschein Binnen'), ('SRC', 'Short Range Certificate'), ('LRC', 'Long Range Certificate')], max_length=3)),
                ('Since', models.DateField()),
                ('LicenseNumber', models.CharField(blank=True, max_length=16)),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cruises.sailor')),
            ],
        ),
        migrations.CreateModel(
            name='cruiseShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SailAs', models.CharField(choices=[('S', 'Schiffer'), ('W', 'Wachführer'), ('C', 'Crew')], default='C', max_length=2)),
                ('Distance', models.FloatField(default=0.0)),
                ('Cruise', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cruises.cruise')),
                ('cosailor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cruises.sailor')),
            ],
        ),
        migrations.AddField(
            model_name='cruise',
            name='sailors',
            field=models.ManyToManyField(blank=True, null=True, through='cruises.cruiseShare', to='cruises.sailor'),
        ),
    ]
