# Generated by Django 3.1.8 on 2021-04-19 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cruise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CruiseName', models.CharField(max_length=128)),
                ('CruiseDescription', models.TextField(blank=True)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('StartPort', models.CharField(max_length=128)),
                ('EndPort', models.CharField(max_length=128)),
                ('MaxBerths', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sailor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Givenname', models.CharField(max_length=64)),
                ('Sirname', models.CharField(max_length=64)),
                ('OwnsPatent', models.CharField(choices=[('S', 'Schiffer'), ('W', 'Wachführer'), ('C', 'Crew')], default='C', max_length=2)),
                ('Member', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='member.profile')),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('SHS', 'Sporthochseeschifferschein'), ('SSS', 'Sportseeschifferschein'), ('SKS', 'Sportlüstenschifferschein'), ('SBS', 'Sportbootführerschein See'), ('SBB', 'Sportbootführerschein Binnen'), ('SRC', 'Short Range Certificate'), ('LRC', 'Long Range Certificate')], max_length=3)),
                ('Since', models.DateField()),
                ('LicenseNumber', models.CharField(max_length=16)),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cruises.sailor')),
            ],
        ),
        migrations.CreateModel(
            name='CruiseShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SailAs', models.CharField(choices=[('S', 'Schiffer'), ('W', 'Wachführer'), ('C', 'Crew')], default='C', max_length=2)),
                ('Distance', models.FloatField()),
                ('Cruise', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cruises.cruise')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='member.profile')),
            ],
        ),
        migrations.AddField(
            model_name='cruise',
            name='Sailors',
            field=models.ManyToManyField(through='cruises.CruiseShare', to='member.profile'),
        ),
    ]
