# Generated by Django 3.2.7 on 2021-10-03 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cruise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('startPort', models.CharField(max_length=128)),
                ('endPort', models.CharField(max_length=128)),
                ('maxBerths', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='patent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('S', 'Schiffer'), ('W', 'Wachführer')], max_length=1)),
                ('Since', models.DateField()),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='license',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('SHS', 'Sporthochseeschifferschein'), ('SSS', 'Sportseeschifferschein'), ('SKS', 'Sportlüstenschifferschein'), ('SBS', 'Sportbootführerschein See'), ('SBB', 'Sportbootführerschein Binnen'), ('SRC', 'Short Range Certificate'), ('LRC', 'Long Range Certificate')], max_length=3)),
                ('Since', models.DateField()),
                ('LicenseNumber', models.CharField(max_length=16)),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='cruiseShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SailAs', models.CharField(choices=[('S', 'Schiffer'), ('W', 'Wachführer'), ('C', 'Crew')], default='C', max_length=2)),
                ('Distance', models.FloatField()),
                ('Cruise', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cruises.cruise')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cruise',
            name='sailors',
            field=models.ManyToManyField(through='cruises.cruiseShare', to=settings.AUTH_USER_MODEL),
        ),
    ]
