# Generated by Django 3.2.18 on 2023-02-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cruise',
            name='sailors',
            field=models.ManyToManyField(blank=True, through='cruises.cruiseShare', to='cruises.sailor'),
        ),
    ]
