# Generated by Django 3.2.9 on 2021-11-26 08:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cruises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cruiseB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='cruise',
            name='sailors',
            field=models.ManyToManyField(blank=True, through='cruises.cruiseShare', to=settings.AUTH_USER_MODEL),
        ),
    ]
