# Generated by Django 3.2.9 on 2021-11-26 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0002_auto_20211126_0809'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cruiseB',
        ),
    ]
