# Generated by Django 3.2.10 on 2021-12-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0004_auto_20211219_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cruiseshare',
            name='Distance',
            field=models.FloatField(default=0.0),
        ),
    ]
