# Generated by Django 3.2.10 on 2022-01-02 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0005_alter_cruiseshare_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sailor',
            name='isNew',
        ),
        migrations.AlterField(
            model_name='cruise',
            name='sailors',
            field=models.ManyToManyField(blank=True, null=True, through='cruises.cruiseShare', to='cruises.sailor'),
        ),
        migrations.AlterField(
            model_name='cruiseshare',
            name='cosailor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cruises.sailor'),
        ),
    ]
