# Generated by Django 3.2.10 on 2022-01-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0006_auto_20220102_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='sailor',
            name='givenName',
            field=models.CharField(default='TEST', max_length=128),
        ),
        migrations.AddField(
            model_name='sailor',
            name='sirName',
            field=models.CharField(default='NUTZER', max_length=128),
        ),
    ]
