# Generated by Django 3.2.10 on 2022-01-03 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0007_auto_20220103_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='sailor',
            name='ownedPatent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cruises.patent'),
        ),
    ]
