# Generated by Django 3.2.10 on 2022-01-03 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0008_sailor_ownedpatent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patent',
            name='Owner',
        ),
    ]
