# Generated by Django 3.2.10 on 2022-01-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0010_alter_patent_since'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patent',
            name='Since',
            field=models.DateField(blank=True, null=True),
        ),
    ]
