# Generated by Django 3.2.10 on 2022-01-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0011_alter_patent_since'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patent',
            name='Type',
            field=models.CharField(choices=[('S', 'Schiffer'), ('W', 'Wachführer'), ('C', 'Crewmitglied')], default='C', max_length=1),
        ),
    ]
