# Generated by Django 3.2.10 on 2022-01-04 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0012_alter_patent_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='Owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cruises.sailor'),
        ),
    ]
