# Generated by Django 3.1.6 on 2021-02-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arbeitskategorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Boot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Arbeitsstundenausschreibung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titel', models.CharField(max_length=512)),
                ('Beschreibung', models.TextField()),
                ('Boote', models.ManyToManyField(to='arbeitsstundenausschreibung.Boot')),
                ('Kategorien', models.ManyToManyField(to='arbeitsstundenausschreibung.Arbeitskategorie')),
                ('Tags', models.ManyToManyField(to='arbeitsstundenausschreibung.Tag')),
            ],
        ),
    ]
