# Generated by Django 3.1.6 on 2021-02-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mitglieder', '0001_initial'),
        ('arbeitsstundenausschreibung', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbeitsstundenausschreibung',
            name='Verantwortlich',
            field=models.ManyToManyField(to='Mitglieder.Profile'),
        ),
        migrations.AlterField(
            model_name='arbeitsstundenausschreibung',
            name='Tags',
            field=models.ManyToManyField(blank=True, to='arbeitsstundenausschreibung.Tag'),
        ),
    ]
