# Generated by Django 3.1.6 on 2021-02-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mitglieder', '0001_initial'),
        ('arbeitsstundenausschreibung', '0002_auto_20210207_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arbeitsstundenausschreibung',
            name='Kategorien',
        ),
        migrations.AlterField(
            model_name='arbeitsstundenausschreibung',
            name='Verantwortlich',
            field=models.ManyToManyField(blank=True, to='Mitglieder.Profile'),
        ),
        migrations.DeleteModel(
            name='Arbeitskategorie',
        ),
    ]
