version: '3.7'

networks:
  # enable connection with Traefik
  traefik:
    name: traefik
  # network for the Database
  backend:
    name: backend

services:
  #---------------------------------------------------------------------------------------
  # Proxy
  #---------------------------------------------------------------------------------------

  reverse-proxy:
    image: traefik:v2.4
    command:
      # Only for development environment
      - --api.insecure=false
      # Get Docker as the provider
      - --providers.docker=true
      # Avoid that all containers are exposed
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=traefik
      - --entrypoints.web_open.address=:80
      - --entryPoints.web.address=:443
      - --log.level=DEBUG
      # HTTPS
      - --providers.file.directory=/configuration/
      - --providers.file.watch=true
      # Redirect
      - --entrypoints.web_open.http.redirections.entryPoint.to=web
      - --entrypoints.web_open.http.redirections.entryPoint.scheme=https
      - --entrypoints.web_open.http.redirections.entrypoint.permanent=true
    security_opt:
      - label:type:docker_t
    ports:
      # The HTTP port
      - "11100:80"
      # HTTPS
      - "11101:443"
      # The Web UI (enabled by --api.insecure=true)
      - "11102:8080"
    volumes:
      # Store certificates in ./letsencrypt/acme.json
      - traefik:/letsencrypt
      # - /Volumes/Transcend/Docker/Proxy:/config
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./InitFiles/traefik/:/configuration/
    networks:
      - traefik

  #---------------------------------------------------------------------------------------
  # Datenbank
  #---------------------------------------------------------------------------------------
  db:
    image: mariadb:latest
    # user: root
    volumes:
      - mariaDB:/var/lib/mysql
      # - /Volumes/Transcend/Docker/DB:/bitnami/mariadb
      - mariaDB:/bitnami/mariadb
      - ./InitFiles/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    command: mysqld --innodb-buffer-pool-size=256M
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]

  #---------------------------------------------------------------------------------------
  # Wiki
  #---------------------------------------------------------------------------------------

  wiki:
    image: mediawiki
    links:
      - db
    volumes:
      - wiki:/var/lib/MediaWiki
    # restart: always
    depends_on:
      - db
      - reverse-proxy
      - SSO
    networks:
      - traefik
      - backend
    labels:
        # The labels are useful for Traefik only
      - "traefik.enable=true"
      - "traefik.http.routers.wiki.entrypoints=web"
      - "traefik.http.routers.wiki.rule=PathPrefix(`/wiki{regex:$$|/.*}`)"
      - "traefik.http.services.wiki.loadbalancer.server.port=80"
      - "traefik.http.routers.wiki.middlewares=wiki-stripprefix"
      - "traefik.http.middlewares.wiki-stripprefix.stripprefix.prefixes=/wiki"
      - "traefik.http.routers.wiki.tls=true"
      - "traefik.http.routers.wiki.tls.certresolver=myresolver"

  #---------------------------------------------------------------------------------------
  # Nextcloud-Redis
  #---------------------------------------------------------------------------------------

  nextcloud-redis:
    image: redis:alpine
    container_name: nextcloud-redis
    hostname: nextcloud-redis
    networks:
      - backend
    restart: unless-stopped
    command: redis-server --requirepass my-secret-pw --appendonly yes
    volumes:
      - redis:/data

  #---------------------------------------------------------------------------------------
  # Nextcloud
  #---------------------------------------------------------------------------------------

  cloud:
    image: nextcloud
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: NextcloudDB
      MYSQL_HOST: db
      OVERWRITEPROTOCOL: http
      OVERWRITEWEBROOT: /cloud
    volumes:
      # - ./InitFiles/cloud:/var/www/html/config
      - cloud:/var/www/html/data
    depends_on:
      - db
      - nextcloud-redis
      - reverse-proxy
      - SSO
    networks:
      - traefik
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cloud.entrypoints=web"
      - "traefik.http.routers.cloud.rule=PathPrefix(`/cloud{regex:$$|/.*}`)"
      - "traefik.http.services.cloud.loadbalancer.server.port=80"
      - "traefik.http.routers.cloud.middlewares=cloud-stripprefix"
      - "traefik.http.middlewares.cloud-stripprefix.stripprefix.prefixes=/cloud"
      - "traefik.http.routers.cloud.tls=true"
      - "traefik.http.routers.cloud.tls.certresolver=myresolver"


  #---------------------------------------------------------------------------------------
  # SSO - Keycloak
  #---------------------------------------------------------------------------------------
  
  SSO:
    image: jboss/keycloak:latest
    restart: always
    environment:
      DB_VENDOR: MARIADB
      DB_ADDR: db
      DB_DATABASE: KeycloackDB
      # Proxy
      # KEYCLOAK_FRONTEND_URL: http://localhost:8080/sso
      PROXY_ADDRESS_FORWARDING: "true"
      KEYCLOAK_IMPORT: "/tmp/realm.json"
    networks:
      - traefik
      - backend
    volumes:
      - ./InitFiles/sso/standalone.xml:/opt/jboss/keycloak/standalone/configuration/standalone.xml
      - ./InitFiles/sso/standalone-ha.xml:/opt/jboss/keycloak/standalone/configuration/standalone-ha.xml
      - ./InitFiles/sso/realm.json:/tmp/realm.json
      - ./InitFiles/sso/themes/asv:/opt/jboss/keycloak/themes/asv
    labels:
      - traefik.enable=true
      - "traefik.http.routers.SSO.entrypoints=web"
      - "traefik.http.routers.SSO.rule=PathPrefix(`/sso{regex:$$|/.*}`)"
      - "traefik.http.services.SSO.loadbalancer.server.port=8080"
      #- "traefik.http.routers.SSO.middlewares=SSO-stripprefix"
      #- "traefik.http.middlewares.SSO-stripprefix.stripprefix.prefixes=/sso"
      - "traefik.http.routers.SSO.tls=true"
      - "traefik.http.routers.SSO.tls.certresolver=myresolver"
    depends_on:
      - db


  #---------------------------------------------------------------------------------------
  # Webpage
  #---------------------------------------------------------------------------------------

  webpage:
    image: webpageimage:0.1
    restart: always
    command: >
      bash -c "python manage.py migrate
      && python manage.py runserver 0.0.0.0:8080"
    volumes:
      - website:/webpage
      - ./Webpage:/opt/Webpage
    environment: 
      # Einstellung für den Client im Keycloak. 
      OIDC_RP_CLIENT_ID: 'website'
      OIDC_RP_SIGN_ALGO: 'RS256'
      DEBUG: "True"
    depends_on:
      - db
      - reverse-proxy
      - SSO
    networks:
      - traefik
      - backend
    labels:
      # The labels are usefull for Traefik only
      - traefik.enable=true
      - "traefik.http.routers.webpage.entrypoints=web"
      - "traefik.http.routers.webpage.rule=PathPrefix(`/`)"
      - "traefik.http.services.webpage.loadbalancer.server.port=8080"
      - "traefik.http.routers.webpage.tls=true"
      - "traefik.http.routers.webpage.tls.certresolver=myresolver"

  #---------------------------------------------------------------------------------------
  # NGINX for Static Files
  #---------------------------------------------------------------------------------------
  StaticFileServer:
    image: nginx
    restart: always
    volumes:
      - ./Webpage/static:/usr/share/nginx/html/static
      - ./InitFiles/staticFileServer/nginx.conf:/usr/local/nginx/conf/nginx.conf
      - ./Webpage/media:/usr/share/nginx/html/media
    networks:
      - traefik
    depends_on: 
      - webpage      
    labels:
      - traefik.enable=true
      - "traefik.http.routers.StaticFileServer.entrypoints=web"
      - "traefik.http.routers.StaticFileServer.rule=PathPrefix(`/static{regex:$$|/.*}`) || PathPrefix(`/media/profile{regex:$$|/.*}`)"
      - "traefik.http.services.StaticFileServer.loadbalancer.server.port=80"
      - "traefik.http.routers.StaticFileServer.tls=true"
      - "traefik.http.routers.StaticFileServer.tls.certresolver=myresolver"

volumes:
  mariaDB:
    driver: local
    name: mariaDB
  wiki:
    driver: local
    name: wiki
  cloud:
    driver: local
    name: cloud
  website:
    driver: local
    name: website
  traefik:
    driver: local
    name: traefik
  redis:
    driver: local
    name: redis