"""
Django settings for Django project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Keyclpack settings
auth_uri = "http://chrisubuntu/auth/realms/sample"
client_id = "Website"
public_uri = "http://chrisubuntu/"

from bossoidc.settings import *
configure_oidc(auth_uri, client_id, public_uri)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '+p32r=0@5ab%chynmfculz8bm9yyo_ot7-3q1-!#8+t0z*llz!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['chrisubuntu', 'localhost', '192.168.2.5']

# Keycloak
KEYCLOAK_OIDC_PROFILE_MODEL = 'django_keycloak.RemoteUserOpenIdConnectProfile'

KEYCLOAK_BEARER_AUTHENTICATION_EXEMPT_PATHS = [
    'admin', 'accounts',
    ]

CONFIG_DIR = os.path.join(os.path.dirname(__file__),os.pardir)

KEYCLOAK_CLIENT_PUBLIC_KEY = """
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkmKKj61ukyS8TWXqjP42SkW/IhYCVgmRB6ooZaUMrEsseJMU+CvFsPs+JQVCN6snbyO4eytytXkCjzykrYq0YKUx+WivfAWmCDFvzryJ8qmRjeBvEj6CEWsGW7vVU0sNzSmJs71mgomQXsaVKnOd5aHDiLttgmzKpvEn/dg87p4BH1FlKR2/agU8tfDRmVO3bXGqiQjlYhq3k8F50K6SKQ8/AEWfMl5OZ9tpSrj9s1tOBa2GOafYSB7D3EV7M1mZ3swiNeU6FPWGmk5SAjcrVbemNRSzz5028I0oPGPj9VMdW3IZu9PSEJCMZ8CQmddyAi1xZYsyplgjXkPpvHmJAwIDAQAB
-----END PUBLIC KEY-----"""


KEYCLOAK_CONFIG = {
    'KEYCLOAK_REALM': 'your-realm',
    'KEYCLOAK_CLIENT_ID': 'your-client',
    'KEYCLOAK_DEFAULT_ACCESS': 'ALLOW', # DENY or ALLOW
    'KEYCLOAK_AUTHORIZATION_CONFIG': os.path.join(CONFIG_DIR , 'authorization-config.json'),
    'KEYCLOAK_METHOD_VALIDATE_TOKEN': 'DECODE',
    'KEYCLOAK_SERVER_URL': 'http://192.168.2.5:11100/sso/auth/',
    'KEYCLOAK_CLIENT_SECRET_KEY': 'your-secret-key',
    'KEYCLOAK_CLIENT_PUBLIC_KEY': KEYCLOAK_CLIENT_PUBLIC_KEY,
}


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'FrontPage',
    'Mitglieder',
    # 'django.contrib.sites',
    'django_keycloak.apps.KeycloakAppConfig',
]

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'bossoidc.backend.OpenIdConnectBackend',
)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_keycloak.middleware.BaseKeycloakMiddleware',
    'django_keycloak.middleware.RemoteUserAuthenticationMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'django_keycloak.auth.backends.KeycloakAuthorizationCodeBackend',
]

ROOT_URLCONF = 'Django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Django.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'websiteDB',
            'USER': 'website',
            'PASSWORD': 'my-secret-pw',
            'HOST': 'db',   # Or an IP Address that your DB is hosted on
            'PORT': 3306,
        }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/
# FORCE_SCRIPT_NAME = '/webpage'
STATIC_URL = '/static/'

# Add these new lines
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static/'),
)

# STATIC_ROOT = '/webpage/'
# os.path.join(BASE_DIR, 'staticfiles')

# FORCE_SCRIPT_NAME = "/webpage/"


# Settings for the Editor
CKEDITOR_SETTINGS = {
    'language': '{{ language }}',
    'toolbar': 'CMS',
    'skin': 'moono-lisa',
}

SITE_ID = 2
