# Generated by Django 3.1.6 on 2021-02-05 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields



class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='position',
            fields=[
                ('titel', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='position_in_the_club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ErnennungsDatum', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hometown', models.CharField(max_length=100, null=True, default='Aachen')),
                ('plz', models.IntegerField(null=True, default=52062)),
                ('country', models.CharField(max_length=70, null=True, default='Deutschland')),
                ('entry_date', models.DateField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('status', models.PositiveSmallIntegerField(models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Anwärter'), (2, 'Aktiv'), (3, 'Inaktiv'), (4, 'AlterHerr')], null=True))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='position_in_the_club',
            name='Mitglied',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.profile'),
        ),
        migrations.AddField(
            model_name='position_in_the_club',
            name='Position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.position'),
        ),
    ]
