# Generated by Django 3.1.7 on 2021-03-24 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='position_in_the_club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ErnennungsDatum', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('titel', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hometown', models.CharField(default='Aachen', max_length=100, null=True)),
                ('plz', models.IntegerField(default=52062, null=True)),
                ('country', models.CharField(default='Deutschland', max_length=70, null=True)),
                ('profile_image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=False, null=True, quality=100, size=[166, 233], upload_to='profile')),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Anwärter'), (2, 'Aktiv'), (3, 'Inaktiv'), (4, 'Alter Herr'), (5, 'Außerordentliches Mitglied'), (6, 'Ehrenmitglied')], null=True)),
                ('entry_date', models.DateField()),
                ('EMail', models.EmailField(max_length=254)),
                ('HandyNummer', models.CharField(max_length=100)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('roles', models.ManyToManyField(to='member.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
