# Generated by Django 3.2.10 on 2022-01-10 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0001_initial'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sailorID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='cruises.sailor'),
        ),
    ]
