# Generated by Django 3.1.6 on 2021-02-16 21:32

from django.db import migrations, models
import member.models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='EMail',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=member.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Heimatstadt',
            field=models.CharField(max_length=100),
        ),
    ]
