# Generated by Django 3.1.7 on 2021-04-05 06:46

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='position',
            new_name='role',
        ),
        migrations.RemoveField(
            model_name='position_in_the_club',
            name='Mitglied',
        ),
        migrations.RemoveField(
            model_name='position_in_the_club',
            name='Position',
        ),
        migrations.AddField(
            model_name='profile',
            name='roles',
            field=models.ManyToManyField(to='member.role'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=False, null=True, quality=100, size=[166, 233], upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Anwärter'), (2, 'Aktiv'), (3, 'Inaktiv'), (4, 'Alter Herr'), (5, 'Außerordentliches Mitglied'), (6, 'Ehrenmitglied')], null=True),
        ),
    ]
