# Generated by Django 3.1.6 on 2021-02-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20210216_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='HandyNummer',
            field=models.CharField(default='0000000', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Heimatstadt',
            field=models.CharField(default='Aachen', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Land',
            field=models.CharField(default='Germany', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='PLZ',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
