# Generated by Django 3.2.11 on 2022-01-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_profile_sailorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='roles',
            field=models.ManyToManyField(blank=True, to='member.role'),
        ),
    ]
