# Generated by Django 3.1.12 on 2021-06-16 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitsstunden', '0002_auto_20210616_1733'),
        ('member', '0002_auto_20210429_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender_role',
            field=models.CharField(choices=[('M', 'Mann'), ('F', 'Frau'), ('X', 'Divers')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='workingHoursAccount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='arbeitsstunden.account'),
        ),
    ]
