# Generated by Django 3.1.6 on 2021-02-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20210216_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Anwärter'), (2, 'Aktiv'), (3, 'Inaktiv'), (4, 'AlterHerr')], null=True),
        ),
    ]
