# Generated by Django 3.2.10 on 2022-01-02 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0006_auto_20220102_1947'),
        ('member', '0003_auto_20210616_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sailorID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='cruises.sailor'),
        ),
    ]
