# Generated by Django 3.1.6 on 2021-02-27 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20210225_2034'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PositionImVerein',
            new_name='position_in_the_club',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='Beschreibung',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='Titel',
            new_name='titel',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Land',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Eintrittsdatum',
            new_name='entry_date',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Heimatstadt',
            new_name='hometown',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='HandyNummer',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='PLZ',
            new_name='plz',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Status',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='PositionImVerein',
        ),
    ]
