# Generated by Django 3.1.6 on 2021-02-05 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('Titel', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('Beschreibung', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PositionImVerein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ErnennungsDatum', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('Titel', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('Beschreibung', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heimatstadt', models.CharField(max_length=45)),
                ('PLZ', models.IntegerField()),
                ('Land', models.CharField(max_length=70)),
                ('Eintrittsdatum', models.DateField()),
                ('EMail', models.EmailField(max_length=254)),
                ('HandyNummer', models.CharField(max_length=100)),
                ('PositionImVerein', models.ManyToManyField(through='Mitglieder.PositionImVerein', to='Mitglieder.Position')),
                ('Status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Mitglieder.status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='positionimverein',
            name='Mitglied',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mitglieder.profile'),
        ),
        migrations.AddField(
            model_name='positionimverein',
            name='Position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mitglieder.position'),
        ),
    ]
