# Generated by Django 3.1.6 on 2021-02-05 18:01

import FrontPage.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPage',
            fields=[
                ('Titel', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Text', models.TextField()),
                ('Beschreibung', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Jahresinfo',
            fields=[
                ('Jahr', models.IntegerField(primary_key=True, serialize=False)),
                ('ZuLeistendeArbeitsstunden', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BlogEintrag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Datum', models.DateField(auto_created=True)),
                ('Titel', models.CharField(max_length=200)),
                ('Text', models.TextField()),
                ('Autor', models.ForeignKey(on_delete=models.SET(FrontPage.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
