# Generated by Django 3.1.6 on 2021-02-06 23:46

from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontPage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogeintrag',
            name='Datum',
        ),
        migrations.RemoveField(
            model_name='blogeintrag',
            name='Text',
        ),
        migrations.AddField(
            model_name='blogeintrag',
            name='DatumErstellt',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='blogeintrag',
            name='Inhalt',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
    ]
