version: '3.3'

networks:
  # enable connection with Traefik
  traefik:
    external: true
    driver: overlay
  # network for the app
  backend:



services:
  #---------------------------------------------------------------------------------------
  # Proxy
  #---------------------------------------------------------------------------------------

  reverse-proxy:
    image: traefik:v2.3
    command:
      # Only for development environment
      - --log.level=INFO
      - --api.insecure=true
      # Get Docker as the provider
      - --providers.docker=true
      # Avoid that all containers are exposed
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=traefik
      - --entryPoints.web.address=:80
    security_opt:
      - label:type:docker_t
    ports:
      # The HTTP port
      - "80:80"
      # HTTPS
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # Store certificates in ./letsencrypt/acme.json
      - /Volumes/Transcend/Docker/letsencrypt:/letsencrypt
      # - /Volumes/Transcend/Docker/Proxy:/config
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik

  #---------------------------------------------------------------------------------------
  # Datenbank
  #---------------------------------------------------------------------------------------
  db:
    image: mariadb
    user: root
    environment:
      MYSQL_ROOT_PASSWORD: "my-secret-pw"
      MYSQL_ROOT_HOST: "%"
    volumes:
      # - /Volumes/Transcend/Docker/DB:/var/lib/mysql
      - /Volumes/Transcend/Docker/DB:/bitnami/mariadb
      # - mariaDB:/bitnami/mariadb
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    ports:
      - 3306
    # command: chmod -R 775 /docker-entrypoint-initdb.d
    networks:
      - backend

  #---------------------------------------------------------------------------------------
  # Wiki
  #---------------------------------------------------------------------------------------

  wiki:
    image: mediawiki
    links:
      - db
    volumes:
      - /Volumes/Transcend/Docker/wiki:/var/lib/MediaWiki
    restart: always
    depends_on:
      - db
      - reverse-proxy
      - SSO
    networks:
      - traefik
      - backend
    labels:
        # The labels are usefull for Traefik only
      - "traefik.enable=true"
      - "traefik.http.routers.wiki.entrypoints=web"
      - "traefik.http.routers.wiki.rule=PathPrefix(`/wiki{regex:$$|/.*}`)"
      - "traefik.http.services.wiki.loadbalancer.server.port=80"
      - "traefik.http.routers.wiki.middlewares=wiki-stripprefix"
      - "traefik.http.middlewares.wiki-stripprefix.stripprefix.prefixes=/wiki"


  #---------------------------------------------------------------------------------------
  # Webpage
  #---------------------------------------------------------------------------------------

  webpage:
    image: webpageimage:0.1
    restart: always
    command: >
      bash -c "python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8080"
    volumes:
      - /Volumes/Transcend/Docker/Webpage:/webpage
    depends_on:
      - db
      - reverse-proxy
      - SSO
    networks:
      - traefik
      - backend
    labels:
      # The labels are usefull for Traefik only
      - traefik.enable=true
      - "traefik.http.routers.webpage.entrypoints=web"
      - "traefik.http.routers.webpage.rule=PathPrefix(`/`)"

  #---------------------------------------------------------------------------------------
  # SSO - Keycloak
  #---------------------------------------------------------------------------------------
  SSO:
    image: quay.io/keycloak/keycloak:latest
    restart: always
    environment:
      DB_VENDOR: MariaDB
      DB_ADDR: db
      DB_DATABASE: KeycloackDB

      DB_USER: Keycloack
      DB_PASSWORD: my-secret-pw

      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
    networks:
      - traefik
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wiki.entrypoints=web"
      - "traefik.http.routers.wiki.rule=PathPrefix(`/SSO{regex:$$|/.*}`)"
      - "traefik.http.services.wiki.loadbalancer.server.port=80"
      - "traefik.http.routers.wiki.middlewares=wiki-stripprefix"
      - "traefik.http.middlewares.wiki-stripprefix.stripprefix.prefixes=/SSO"


volumes:
  mariaDB:
    driver: local