version: '3.3'

services:
  #---------------------------------------
  # Proxy
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    expose:
      - 80
      - 443
    volumes:
      - /Docker/nginx/config:/etc/ngnix
      - /Docker/nginx/certificate:/etc/ssl/private
      - /var/run/docker.sock:/tmp/docker.sock

  #---------------------------------------
  # Datenbank
  db:
    image: mysql
    environment:
      MYSQL_Name: TESTDB
      MYSQL_User: Webpage
      MYSQL_PASSWORD: IMATESTPAGE
      MYSQL_ROOT_PASSWORD: my-secret-pw
    volumes:
      - /Docker/DB:/var/lib/mysql
    restart: always

  #---------------------------------------
  # Wiki
  wiki:
    image: mediawiki
    links:
      - db
    volumes:
      - /Docker/wiki:/var/lib/MediaWiki
    environment:
      - "VIRTUAL_HOST=wiki.chrisubuntu"
      - "VIRTUAL_PORT=8081"
    restart: always
    ports:
      - "40511:80"

  #---------------------------------------
  # Webpage
  Webpage:
    image: webpageimage:0.1
    environment:
      - "VIRTUAL_HOST=web.chrisubuntu"
      - "VIRTUAL_PORT=8080"
    restart: always
    command: python manage.py runserver 0.0.0.0:8080
    ports:
      - "40510:8080"
    volumes:
      - /Docker/Webpage:/webpage
    depends_on:
      - db
      - nginx-proxy


volumes:
  db_data: {}
  wiki_data: {}
  page_data: {}


networks:
  default:
    external:
      name: nginx-proxy