version: 3.1

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_User: Webpage
      MYSQL_PASSWORD: IMATESTPAGE
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3308:3306"