# Generated by Django 3.1.8 on 2021-04-29 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms
import jollen.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bootsklasse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='nachricht_historie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('text', models.CharField(max_length=800)),
                ('autor', models.ForeignKey(on_delete=models.SET(jollen.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='nachricht',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'segelbar'), (2, 'eingeschränkt segelbar'), (3, 'nicht segelbar'), (4, 'Fertig für die Indienststellung')], default=3)),
                ('standort', models.PositiveSmallIntegerField(choices=[(1, 'Rursee'), (2, 'Roermond'), (3, 'Eschweiler'), (4, 'Aachen'), (5, 'Segellager'), (6, 'unterwegs')], default=3)),
                ('text', models.CharField(max_length=800)),
                ('autor', models.ForeignKey(on_delete=models.SET(jollen.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='boot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', tinymce.models.HTMLField()),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=False, null=True, quality=100, size=[166, 233], upload_to='boats')),
                ('obman', models.CharField(max_length=100)),
                ('isboat', models.BooleanField(default=True)),
                ('history', models.ManyToManyField(blank=True, to='jollen.nachricht_historie')),
                ('klasse', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jollen.bootsklasse')),
                ('message', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jollen.nachricht')),
            ],
        ),
    ]
