# Generated by Django 3.1.8 on 2021-04-29 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jollen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boot',
            name='message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jollen.nachricht'),
        ),
    ]
