# Generated by Django 3.1.8 on 2021-05-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jollen', '0003_auto_20210429_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nachricht',
            name='standort',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Rursee'), (3, 'Eschweiler'), (4, 'Aachen'), (5, 'Segellager'), (6, 'unterwegs')], default=3),
        ),
    ]
