# Generated by Django 3.2.18 on 2023-02-18 20:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jollen', '0004_auto_20210508_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boot',
            name='obman',
        ),
        migrations.AddField(
            model_name='boot',
            name='obman',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
