# Generated by Django 3.2.18 on 2023-02-18 21:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jollen', '0005_auto_20230218_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boot',
            name='obman',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
