# Generated by Django 3.1.6 on 2021-02-05 18:01

import blog.models
import blog.models
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='blogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_Created', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('titel', models.CharField(max_length=200)),
                ('text', tinymce.models.HTMLField()),
                ('last_editor', models.CharField(max_length=300)),
                ('author', models.ForeignKey(on_delete=models.SET(blog.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('history', models.ManyToManyField(to='blog.blogPostHistory')),
            ],
        ),
        migrations.CreateModel(
            name='blogPostHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('titel', models.CharField(max_length=200)),
                ('text', tinymce.models.HTMLField()),
                ('editor', models.CharField(max_length=300)),
            ],
        ),
    ]
