# Generated by Django 3.1.7 on 2021-04-03 20:37

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_Created', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('titel', models.CharField(max_length=200)),
                ('text', tinymce.models.HTMLField()),
                ('last_editor', models.CharField(max_length=300)),
                ('author', models.ForeignKey(on_delete=models.SET(blog.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='blogPostHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('titel', models.CharField(max_length=200)),
                ('text', tinymce.models.HTMLField()),
                ('editor', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='BlogEintrag',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='history',
            field=models.ManyToManyField(to='blog.blogPostHistory'),
        ),
    ]
