# Generated by Django 3.1.8 on 2021-04-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='history',
            field=models.ManyToManyField(blank=True, to='blog.blogPostHistory'),
        ),
    ]
