# Generated by Django 3.1.7 on 2021-03-24 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arbeitsbeteiligung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Arbeitszeit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Saison',
            fields=[
                ('Jahr', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Projekt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256)),
                ('Beschreibung', models.TextField(blank=True)),
                ('Saison', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='arbeitsstunden.saison')),
                ('Verantwortlich', models.ManyToManyField(to='member.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Arbeitsstundenausschreibung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titel', models.CharField(max_length=512)),
                ('Beschreibung', models.TextField()),
                ('Umfang', models.CharField(blank=True, max_length=512)),
                ('Fertigstellungstermin', models.DateField(blank=True, null=True)),
                ('Projekt', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='arbeitsstunden.projekt')),
                ('Tags', models.ManyToManyField(blank=True, to='arbeitsstunden.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Arbeitseinheit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Beschreibung', models.CharField(max_length=1024)),
                ('Datum', models.DateField()),
                ('Ausschreibung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arbeitsstunden.arbeitsstundenausschreibung')),
                ('Beteiligte', models.ManyToManyField(through='arbeitsstunden.Arbeitsbeteiligung', to='member.profile')),
                ('Projekt', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='arbeitsstunden.projekt')),
            ],
        ),
        migrations.AddField(
            model_name='arbeitsbeteiligung',
            name='Arbeitseinheit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='arbeitsstunden.arbeitseinheit'),
        ),
        migrations.AddField(
            model_name='arbeitsbeteiligung',
            name='Arbeitsleistender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='member.profile'),
        ),
    ]
