# Generated by Django 3.1.6 on 2021-02-14 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Mitglieder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Projekt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256)),
                ('Beschreibung', models.TextField(blank=True)),
                ('Verantwortlich', models.ManyToManyField(blank=True, to='Mitglieder.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Arbeitsstundenausschreibung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titel', models.CharField(max_length=512)),
                ('Beschreibung', models.TextField()),
                ('Umfang', models.CharField(blank=True, max_length=512)),
                ('Fertigstellungstermin', models.DateField(blank=True, null=True)),
                ('Projekt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='arbeitsstunden.projekt')),
                ('Tags', models.ManyToManyField(blank=True, to='arbeitsstunden.Tag')),
            ],
        ),
    ]
