# Generated by Django 3.1.12 on 2021-06-16 17:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arbeitsstunden', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isNew', models.BooleanField(default=False)),
                ('hasShortenedHours', models.BooleanField(default=False)),
                ('name', models.CharField(default='TESTNUTZER', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='costCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='customHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customHours', models.IntegerField(null=True)),
                ('percentege', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('planedHours', models.IntegerField(blank=True)),
                ('aktiv', models.BooleanField(default=True)),
                ('costCenter', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='arbeitsstunden.costcenter')),
                ('responsible', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='season',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
                ('hours', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='subproject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=500)),
                ('voluntary', models.BooleanField(default=False)),
                ('planed', models.BooleanField(default=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('planedHours', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('setupDate', models.DateField(default=datetime.date.today)),
                ('employee', models.ManyToManyField(blank=True, to='arbeitsstunden.account')),
            ],
        ),
        migrations.RemoveField(
            model_name='arbeitseinheit',
            name='Ausschreibung',
        ),
        migrations.RemoveField(
            model_name='arbeitseinheit',
            name='Beteiligte',
        ),
        migrations.RemoveField(
            model_name='arbeitseinheit',
            name='Projekt',
        ),
        migrations.RemoveField(
            model_name='arbeitsstundenausschreibung',
            name='Projekt',
        ),
        migrations.RemoveField(
            model_name='arbeitsstundenausschreibung',
            name='Tags',
        ),
        migrations.RemoveField(
            model_name='projekt',
            name='Saison',
        ),
        migrations.RemoveField(
            model_name='projekt',
            name='Verantwortlich',
        ),
        migrations.DeleteModel(
            name='Arbeitsbeteiligung',
        ),
        migrations.DeleteModel(
            name='Arbeitseinheit',
        ),
        migrations.DeleteModel(
            name='Arbeitsstundenausschreibung',
        ),
        migrations.DeleteModel(
            name='Projekt',
        ),
        migrations.DeleteModel(
            name='Saison',
        ),
        migrations.AddField(
            model_name='subproject',
            name='parts',
            field=models.ManyToManyField(blank=True, to='arbeitsstunden.work'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='arbeitsstunden.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='arbeitsstunden.season'),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, to='arbeitsstunden.tag'),
        ),
        migrations.AddField(
            model_name='customhours',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arbeitsstunden.season'),
        ),
        migrations.AddField(
            model_name='customhours',
            name='used_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arbeitsstunden.account'),
        ),
    ]
