# Generated by Django 3.1.6 on 2021-02-14 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mitglieder', '0001_initial'),
        ('arbeitsstunden', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arbeitsbeteiligung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Arbeitszeit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Saison',
            fields=[
                ('Jahr', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='arbeitsstundenausschreibung',
            name='Projekt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='arbeitsstunden.projekt'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projekt',
            name='Verantwortlich',
            field=models.ManyToManyField(to='Mitglieder.Profile'),
        ),
        migrations.CreateModel(
            name='Arbeitseinheit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Beschreibung', models.CharField(max_length=1024)),
                ('Ausschreibung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arbeitsstunden.arbeitsstundenausschreibung')),
                ('Beteiligte', models.ManyToManyField(through='arbeitsstunden.Arbeitsbeteiligung', to='Mitglieder.Profile')),
                ('Projekt', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='arbeitsstunden.projekt')),
            ],
        ),
        migrations.AddField(
            model_name='arbeitsbeteiligung',
            name='Arbeitseinheit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='arbeitsstunden.arbeitseinheit'),
        ),
        migrations.AddField(
            model_name='arbeitsbeteiligung',
            name='Arbeitsleistender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Mitglieder.profile'),
        ),
        migrations.AddField(
            model_name='projekt',
            name='Saison',
            field=models.ForeignKey(default=2020, on_delete=django.db.models.deletion.RESTRICT, to='arbeitsstunden.saison'),
            preserve_default=False,
        ),
    ]
