# Generated by Django 3.1.12 on 2021-06-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitsstunden', '0004_auto_20210616_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, to='arbeitsstunden.tag'),
        ),
    ]
