# Generated by Django 3.1.12 on 2021-06-23 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitsstunden', '0007_auto_20210623_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='arbeitsstunden.season'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, to='arbeitsstunden.tag'),
        ),
    ]
