# Generated by Django 3.1.12 on 2021-06-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitsstunden', '0008_auto_20210623_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='planedHours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, to='arbeitsstunden.tag'),
        ),
    ]
