# Generated by Django 3.1.12 on 2021-06-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitsstunden', '0010_auto_20210623_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, to='arbeitsstunden.tag'),
        ),
        migrations.AlterField(
            model_name='work',
            name='employee',
            field=models.ManyToManyField(blank=True, null=True, to='arbeitsstunden.account'),
        ),
    ]
