# Generated by Django 3.1.12 on 2021-06-25 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitsstunden', '0012_auto_20210625_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, to='arbeitsstunden.tag'),
        ),
        migrations.AlterField(
            model_name='work',
            name='setupDate',
            field=models.DateField(default=datetime.date(2021, 6, 25)),
        ),
    ]
