# Generated by Django 3.2.4 on 2021-07-05 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitsstunden', '0013_auto_20210625_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, to='arbeitsstunden.tag'),
        ),
        migrations.AlterField(
            model_name='work',
            name='setupDate',
            field=models.DateField(default=datetime.date(2021, 7, 5)),
        ),
    ]
