# Generated by Django 3.2.5 on 2021-07-18 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitsstunden', '0015_auto_20210718_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customhours',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arbeitsstunden.season'),
        ),
        migrations.AlterField(
            model_name='customhours',
            name='used_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arbeitsstunden.account'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, to='arbeitsstunden.tag'),
        ),
        migrations.AlterUniqueTogether(
            name='customhours',
            unique_together={('season', 'used_account')},
        ),
    ]
