# Generated by Django 3.2.5 on 2021-07-18 11:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arbeitsstunden', '0017_auto_20210718_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='responsible',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, to='arbeitsstunden.tag'),
        ),
    ]
