# Generated by Django 3.2.8 on 2021-10-12 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitsstunden', '0018_auto_20210718_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='customhours',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'ACTIVE'), (2, 'GUEST'), (3, 'INACTIVE'), (4, 'OLD_MAN'), (5, 'PROSPECT'), (6, 'QUIT')], null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, to='arbeitsstunden.tag'),
        ),
        migrations.AlterField(
            model_name='work',
            name='setupDate',
            field=models.DateField(default=datetime.date(2021, 10, 12)),
        ),
    ]
