# Generated by Django 3.1.7 on 2021-03-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPage',
            fields=[
                ('Titel', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Text', models.TextField()),
                ('Beschreibung', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Jahresinfo',
            fields=[
                ('Jahr', models.IntegerField(primary_key=True, serialize=False)),
                ('ZuLeistendeArbeitsstunden', models.IntegerField()),
            ],
        ),
    ]
