# Generated by Django 3.1.8 on 2021-04-08 07:14

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='standartPages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('text', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='HeadPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=50)),
                ('text', tinymce.models.HTMLField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='infoPageHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_Editor', models.CharField(max_length=200)),
                ('titel', models.CharField(max_length=200)),
                ('text', tinymce.models.HTMLField()),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=200, unique=True)),
                ('datum', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Jahresinfo',
            fields=[
                ('Jahr', models.IntegerField(primary_key=True, serialize=False)),
                ('ZuLeistendeArbeitsstunden', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='subThemen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='infoPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('text', tinymce.models.HTMLField()),
                ('name', models.CharField(max_length=200)),
                ('headPage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.headpage')),
                ('history', models.ManyToManyField(to='web.infoPageHistory')),
            ],
        ),
        migrations.AddField(
            model_name='headpage',
            name='history',
            field=models.ManyToManyField(to='web.infoPageHistory'),
        ),
        migrations.CreateModel(
            name='frontHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='left', to='web.headpage')),
                ('right', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='right', to='web.headpage')),
            ],
        ),
    ]
