# Generated by Django 3.1.8 on 2021-04-29 18:05

from django.db import migrations, models
import django_resized.forms
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headpage',
            name='history',
            field=models.ManyToManyField(blank=True, to='web.infoPageHistory'),
        ),
        migrations.AlterField(
            model_name='headpage',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=False, null=True, quality=100, size=[166, 233], upload_to='frontPage'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='history',
            field=models.ManyToManyField(blank=True, to='web.infoPageHistory'),
        ),
        migrations.AlterField(
            model_name='infopagehistory',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
