# Generated by Django 3.1.7 on 2021-04-03 20:37

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='subThemen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='infopage',
            old_name='Beschreibung',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='infopage',
            old_name='Titel',
            new_name='titel',
        ),
        migrations.RemoveField(
            model_name='infopage',
            name='Text',
        ),
        migrations.AddField(
            model_name='infopage',
            name='name',
            field=models.CharField(default='default', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infopage',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[('SL', 'Segeln lernen'), ('V', 'Der Verein'), ('See', 'Seeschiff'), ('J', 'Jollenpark'), ('A', 'Aktivitäten')], default=4),
        ),
        migrations.AddField(
            model_name='infopage',
            name='text',
            field=tinymce.models.HTMLField(default='default'),
            preserve_default=False,
        ),
    ]
