# Generated by Django 3.1.8 on 2021-04-19 09:52

from django.db import migrations, models
import django_resized.forms
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='standartPages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('text', tinymce.models.HTMLField()),
            ],
        ),
        migrations.AlterField(
            model_name='headpage',
            name='history',
            field=models.ManyToManyField(blank=True, to='web.infoPageHistory'),
        ),
        migrations.AlterField(
            model_name='headpage',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=False, null=True, quality=100, size=[166, 233], upload_to='frontPage'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='history',
            field=models.ManyToManyField(blank=True, to='web.infoPageHistory'),
        ),
        migrations.AlterField(
            model_name='infopagehistory',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
