# Generated by Django 3.1.8 on 2021-05-18 14:15

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210429_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='sponsoren',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=200)),
                ('sponsorenBild', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=False, null=True, quality=100, size=[376, 139], upload_to='sponsoren')),
                ('logo', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=False, null=True, quality=100, size=[180, 157], upload_to='sponsoren')),
            ],
        ),
    ]
