# Generated by Django 3.1.8 on 2021-04-18 08:54

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210408_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='standartPages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('text', tinymce.models.HTMLField()),
            ],
        ),
        migrations.AlterField(
            model_name='headpage',
            name='history',
            field=models.ManyToManyField(blank=True, to='web.infoPageHistory'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='history',
            field=models.ManyToManyField(blank=True, to='web.infoPageHistory'),
        ),
    ]
