# Generated by Django 3.1.7 on 2021-04-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210403_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infopage',
            name='status',
            field=models.CharField(choices=[('SL', 'Segeln lernen'), ('V', 'Der Verein'), ('See', 'Seeschiff'), ('J', 'Jollenpark'), ('A', 'Aktivitäten')], default='SL', max_length=3),
        ),
    ]
