# Generated by Django 3.1.8 on 2021-04-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210408_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headpage',
            name='history',
            field=models.ManyToManyField(blank=True, to='web.infoPageHistory'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='history',
            field=models.ManyToManyField(blank=True, to='web.infoPageHistory'),
        ),
    ]
