# Generated by Django 3.1.12 on 2021-06-16 17:33

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_sponsoren'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsoren',
            name='logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=False, null=True, quality=100, size=[549, 240], upload_to='sponsoren'),
        ),
        migrations.AlterField(
            model_name='sponsoren',
            name='sponsorenBild',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=False, null=True, quality=100, size=[549, 240], upload_to='sponsoren'),
        ),
    ]
