# Generated by Django 3.1.7 on 2021-04-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20210403_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infopage',
            name='titel',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='infopage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),

    ]
