# Generated by Django 3.1.8 on 2021-04-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20210418_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headpage',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
