# Generated by Django 3.2.4 on 2021-07-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20210616_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsoren',
            name='logo',
            field=models.ImageField(upload_to='sponsoren'),
        ),
        migrations.AlterField(
            model_name='sponsoren',
            name='sponsorenBild',
            field=models.ImageField(upload_to='sponsoren'),
        ),
    ]
