# Generated by Django 3.1.7 on 2021-04-05 11:18

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20210403_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='infoPageHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_Editor', models.CharField(max_length=200)),
                ('titel', models.CharField(max_length=200)),
                ('text', tinymce.models.HTMLField()),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=200, unique=True)),
                ('datum', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='infopage',
            name='history',
            field=models.ManyToManyField(to='web.infoPageHistory'),
        ),
    ]
